### PR TITLE
feat: allow overriding headerLayoutInterpolator

### PR DESCRIPTION
**Pull request by ForbesLindesay**
This makes it possible to do animations where the header does not come in from the left when navigating from one screen to another.

### CODE REVIEW

**Comment by ForbesLindesay** [comment]
I'm still struggling to get the effect quite right, but I think I'm just getting the interpolater function wrong.

**Comment by brentvatne** [comment]
this looks fine to me, thanks

**Comment by satya164** [comment]
Do you want to update the PR to fix conflicts @ForbesLindesay ?

**Comment by satya164** [comment]
Closing due to no response

**Pull request closed without merging**
