### PR TITLE
change header for accept element children

### PR DESCRIPTION
**Pull request by misaku**
has many kind of bar in community, with this change is possible use more bars

### CODE REVIEW

**Comment by misaku** [comment]
What do I need to convince that is good for the project?

**Comment by brentvatne** [comment]
hello! i don't understand this really, can you give some examples of how you would use this more concretely?

**Comment by misaku** [comment]
for exemple if i wouldlike preserve prop of header and use other e custom header, i can change content if i modify this.

**Comment by misaku** [comment]
im my project i use react-navigation, [react-navigation-collapsible](https://github.com/benevbright/react-navigation-collapsible) and [header of react-native-material-ui](https://github.com/xotahal/react-native-material-ui/blob/master/docs/Demo.md), if i use collapsible and navigation is ok, but i cant use custom header,  so if has accept element children, no have problem  and all of elements works ok

**Comment by brentvatne** [comment]
can you add an example to the example project in this that uses one of those so i can see it in action?

**Comment by satya164** [comment]
Closing due to no response

**Pull request closed without merging**
