### PR TITLE
docs: Add missing peer dependency in README

### PR DESCRIPTION
**Pull request by mars-lan**

### CODE REVIEW

**Comment by Rapsssito** [comment]
@mars-lan, please, rename your PR to `docs: Add missing peer dependency in README`

**Comment by mars-lan** [comment]
@Rapsssito Done

**Comment by mars-lan** [comment]
@3imed-jaberi  @Rapsssito  can either of you merge this in. I have no write access.

**Comment by 3imed-jaberi** [comment]
Also, I haven't access.. I just help by make a review ..

ping @satya164  @osdnk @eriveltonelias ..etc

**Pull request merged**
